insert into books (title, genre) values ('The Great Adventure', 'Adventure');
insert into books (title, genre) values ('Mystery of the Unknown', 'Mystery');
insert into books (title, genre) values ('Love in the Time of Science', 'Romance');
insert into books (title, genre) values ('Future Horizons', 'Science Fiction');
insert into books (title, genre) values ('The Silent Forest', 'Drama');
insert into books (title, genre) values ('Echoes of Eternity', 'Fantasy');
insert into books (title, genre) values ('Beneath the Waves', 'Adventure');
insert into books (title, genre) values ('Crimson Dawn', 'Thriller');
insert into books (title, genre) values ('The Forgotten Tales', 'Historical Fiction');
insert into books (title, genre) values ('Dancing with Stars', 'Romance');
insert into books (title, genre) values ('The Quantum Paradox', 'Science Fiction');
insert into books (title, genre) values ('Shadows and Secrets', 'Mystery');
insert into books (title, genre) values ('Whispers of the Past', 'Drama');
insert into books (title, genre) values ('Legends of Aramoor', 'Fantasy');
insert into books (title, genre) values ('Rising Storm', 'Thriller');
insert into books (title, genre) values ('The Alchemist’s Code', 'Adventure');
insert into books (title, genre) values ('Chronicles of Mythica', 'Fantasy');
insert into books (title, genre) values ('Midnight Express', 'Thriller');
insert into books (title, genre) values ('Dreams of Tomorrow', 'Science Fiction');
insert into books (title, genre) values ('The Last Symphony', 'Drama');
