insert into authors (fullName, nationality, book_id) values ('John Smith', 'American', 1);
insert into authors (fullName, nationality, book_id) values ('Emma Brown', 'British', 2);
insert into authors (fullName, nationality, book_id) values ('Carlos Santos', 'Brazilian', 3);
insert into authors (fullName, nationality, book_id) values ('Sophia Lee', 'Canadian', 4);
insert into authors (fullName, nationality, book_id) values ('Liam O’Connor', 'Irish', 5);
insert into authors (fullName, nationality, book_id) values ('Ava Chen', 'Chinese', 6);
insert into authors (fullName, nationality, book_id) values ('Ethan Davis', 'Australian', 7);
insert into authors (fullName, nationality, book_id) values ('Isabella Rossi', 'Italian', 8);
insert into authors (fullName, nationality, book_id) values ('Noah Garcia', 'Spanish', 9);
insert into authors (fullName, nationality, book_id) values ('Mia Patel', 'Indian', 10);
insert into authors (fullName, nationality, book_id) values ('Alexander Müller', 'German', 11);
insert into authors (fullName, nationality, book_id) values ('Olivia Nguyen', 'Vietnamese', 12);
insert into authors (fullName, nationality, book_id) values ('William Johnson', 'South African', 13);
insert into authors (fullName, nationality, book_id) values ('Charlotte Dubois', 'French', 14);
insert into authors (fullName, nationality, book_id) values ('James Wilson', 'New Zealander', 15);
insert into authors (fullName, nationality, book_id) values ('Amelia Carter', 'Canadian', 16);
insert into authors (fullName, nationality, book_id) values ('Lucas Fernández', 'Argentine', 17);
insert into authors (fullName, nationality, book_id) values ('Ella White', 'American', 18);
insert into authors (fullName, nationality, book_id) values ('Benjamin Kim', 'Korean', 19);
insert into authors (fullName, nationality, book_id) values ('Emily Clarke', 'British', 20);
